apiVersion: v1
kind: Namespace
metadata:
  name: openbao
  labels:
    app.kubernetes.io/part-of: collabio-provider-stack
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
  labels:
    app.kubernetes.io/part-of: collabio-provider-stack
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: Namespace
metadata:
  name: collabio-provider-tests
  labels:
    app.kubernetes.io/part-of: collabio-provider-stack
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openbao-independent-rwo
  labels:
    app.kubernetes.io/part-of: collabio-provider-stack
provisioner: rancher.io/local-path
reclaimPolicy: Retain
allowVolumeExpansion: false
volumeBindingMode: WaitForFirstConsumer
